### ISSUE TITLE
Hardware design. 

### ISSUE THREAD

**Issue by tbitson** [Blackaddr/BALibrary#8]
Beautiful design.  I’m really impressed. For software dev work, Is the full hardware design package (eagle or whatever you used) available? Board layout, all dimensions, etc. I’d like to design a custom enclosure that allows access to all buttons and controls, as well as the expansion and test connectors.

**Comment by Blackaddr** [comment]
The software and electrical schematics are all public in order to make it easy to integrate into custom projects. The PCB design files (gerber) are kept private as much of the unique product quality (low noise, low interference) comes from the mixed-signal PCB design techniques employed. 
Mechanical dimensions and and drilling guide are included in the datasheet. You can find the link on the Tindie product page.
[https://www.tindie.com/products/Blackaddr/arduino-teensy-guitar-audio-shield/](url)
If customers need a particular measurement not included in the mech drawing I can provide that no problem.

**Comment by tbitson** [comment]
Thanks!

**Comment by nickajeglin** [comment]
Is there a general schematic, or hardware block diagram for using the sram? I'd like to use your library in a eurorack module, so I would want to adjust the footprint of the hardware to fit into that format. Ie: 1/8 inch jacks, remove midi input, add parameter control via +/- 5v CV signals, with associated input protection, add audio input handling hardware to cope with synth line levels, etc. I can work out most of this myself, but having a block diagram of what the library expects hardware wise would be super useful since I have little teensy experience and I'm not familiar with SRAM

**Comment by nickajeglin** [comment]
Just found the schematics in the manual for your guitar board. Am I ok to make derivative work for non-commercial use based off of the schematics? As I mentioned above I'd be changing it pretty significantly, and my PCB design would almost certainly be lower quality than yours! Let me know if you're ok with that. I wouldn't be selling any PCB's, although I like to give away spares to friends and other diy audio enthusiasts.

**Comment by Blackaddr** [comment]
Feel free to use the schematic and BALibrary software for personal use. As
for SRAM, they just use a standard SPI interface. My BALibrary uses some
convenience classes to wrap them up and make DMA easier on the Teensy 3.X
devices.
